language: node_js
node_js:
  - 'lts/*'
install:
  - npm install
  - npm run bootstrap
  - npm install -g surge
script:
  - npm run build:doc
dx-scan:
  stage: build
  image: dxheroes/dx-scanner:latest
  script:
    - dx-scanner run --ci
